### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by POSTiGA1** [BGInfinityX/Dark-Matter-Layer-7-DDoS#3]
Hello Sir 

May i ask right command to start ?

**Comment by BGInfinityX** [comment]
Okay, the command is: python DarkMatter.py

**Comment by POSTiGA1** [comment]
Hello Sir

I got below error, running with VPS 16vcore AMD , 32GB RAM 
` python3 DarkMatter.py
Welcome To DarkMatter DDoS
IP/Domain: https://176.9.16.251/HIT
Port: 80
[>>>] Starting the attack [<<<]
Traceback (most recent call last):
  File "DarkMatter.py", line 58, in <module>
    send2attack() #61 lines for the most powerful attack, cool?
  File "DarkMatter.py", line 56, in send2attack
    mp.start() #Magic Starts
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 65, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
`

**Comment by BGInfinityX** [comment]
You should not use http:// or https://, use only the ip, i will add support for this in the next version, about your error, you just need to type a command in your VPS shell/bash: ulimit -n 999999
