### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by empfaked** [BGInfinityX/Dark-Matter-Layer-7-DDoS#4]
dont work help
Traceback (most recent call last):
  File "DarkMatter.py", line 58, in <module>
    send2attack() #61 lines for the most powerful attack, cool?
  File "DarkMatter.py", line 56, in send2attack
    mp.start() #Magic Starts
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by BGInfinityX** [comment]
Do this command in your linux shell: ulimit -n 999999
