### ISSUE TITLE
Error To many open files...

### ISSUE THREAD

**Issue by Xeroxxhah** [BGInfinityX/Dark-Matter-Layer-7-DDoS#6]
python3 DarkMatter.py      
Welcome To DarkMatter DDoS
IP/Domain: vaporvm.vic
Port: 80
[>>>] Starting the attack [<<<]
Traceback (most recent call last):
  File "DarkMatter.py", line 58, in <module>
    send2attack() #61 lines for the most powerful attack, cool?
  File "DarkMatter.py", line 56, in send2attack
    mp.start() #Magic Starts
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 26, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 36, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the Tuple table

Original exception was:
Traceback (most recent call last):
  File "DarkMatter.py", line 58, in <module>
    send2attack() #61 lines for the most powerful attack, cool?
  File "DarkMatter.py", line 56, in send2attack
    mp.start() #Magic Starts
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by cliffprogram** [comment]
we're same

**Comment by Xeroxxhah** [comment]
I think its due to opening 5000 processes at a time.

**Comment by BGInfinityX** [comment]
You can fix this, run this command in the shell: ulimit -n 99999
